### PR TITLE
Remove RestClient dependency

### PR DESCRIPTION
**Pull request by adamof**
### But why?
I was having an issue with creating routes with the mailgun + RestClient, since the parameters were not properly passed to Mailgun's API. https://gist.github.com/adamof/631bd6e02dd6f092c423c089552af712
I tried making the request with the ruby built-in Net:HTTP and it succeeded so I thought this is a good reason to get rid of the dependency on RestClient.

### What have I done
🔧 I have fixed the RSpec failures and changed the expectations to conform to the new RSpec `expect(foo).to bar`
♻️  Switched to using pry for debugging, because of the nice colour scheme, unlike `byebug` 
🔪  Removed a dependency on the rails `stringify_keys` method
🚒  Improved the error handling and raising. Previously the message containing the failure reason was not passed to the exception object. For example routes creation 400 Bad Request exceptions did not have the message "Expression is missing".
📤  Most importantly I have removed RestClient and replaced it with built-in Net::HTTP library, which is tested with WebMock to ensure that the correct requests are made.

### Further work
I have made no changes to the interface of `Mailgun::Base.submit` so that this change gets live quicker. We could stop passing the full url with auth to `submit` every time and instead just pass the path and params and take the auth and url from the config settings.

### Closing notes
I have tested this in our production environment and I've had no issues creating/updating/deleting domains, routes, messages and webhooks. 
I am open to any suggestions how to improve this, since this is my first major contribution to a public gem.

### CODE REVIEW

**Comment by HashNuke** [comment]
@adamof Thank you very much for this PR. I'll try it out this weekend and merge it.
I'll also add it on a CI so that tests can be run.

**Comment by adamof** [comment]
Hey @HashNuke, CI sounds like a great idea given that a lot of CI services are free for open-source projects! :)

**Comment by adamof** [comment]
If you don't have the time, I could set this up if you give me permissions over the repo :)

**Comment by HashNuke** [comment]
@adamof Sorry. Looked at it when I woke up the other day and forgot to reply to this PR. You now have commit access to this repo. I've also added the repo to TravisCI. Let me know if you need to add config keys to Travis. I'm assuming we'll have to add a mailgun api key to run tests using VCR (if we make those changes).

**Comment by HashNuke** [comment]
@adamof Thank you for the PR. Skimmed through it. Looks very detailed. I'll let you do the honours by merging your PR too :)

**Comment by HashNuke** [comment]
@adamof If you add a travis config, you can push to github and view your tests here - https://travis-ci.org/HashNuke/mailgun
We can add a TravisCI badge to the readme.

**Comment by adamof** [comment]
@HashNuke I've added config for Travis CI, I've added Ruby 2.0, 2.1, 2.2 and 2.3 to the build matrix. Do you think we need to test more?
But I don't seem to be able to merge the PR myself.

I've also added the build status to the README.

**Comment by HashNuke** [comment]
@adamof you will have to accept the invitation on email. Only then github will allow you to commit to this repo.

Yes those ruby versions are sufficient for now.

**Comment by HashNuke** [comment]
@adamof b/w Huge thank you ~! ❤️
77 examples run and passed on Travis on 4 diff ruby versions.

**Comment by adamof** [comment]
👯 
How do you decide when to release a new gem version? :)

**Comment by HashNuke** [comment]
@adamof There's a new v0.9 just published to rubygems. Sorry about the delay and thanks for contributing ~!

**Pull request merged**
